version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: congreso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_NAME=congreso
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_HOST=db
    depends_on:
      - db
